---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: connectopia-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/prod/microk8s/www.connectopia.social
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

