---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: old1-w-influencers-app
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./apps/prod/mow/old1.w-influencers.com
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

