---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: w-influencers-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/prod/microk8s/www.w-influencers.com
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

