apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  strategy:
    type: Recreate
  template:
    metadata:
      name: db-pod
      labels:
        type: db
    spec:
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
        - name: mysql-root-passwd
          configMap:
            name: mysql-root-passwd
      containers:
        - name: db-container
          image: mysql:5.7
         # ports:
        #    - containerPort: 3306
          args:
          - --character-set-server=utf8mb4
          #- --default-authentication-plugin=mysql_native_password
          env:
          - name: TZ
            value: America/New_York
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
                optional: false # same as default; "mysecret" must exist and include a key named "password"
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
                optional: false # same as default; "mysecret" must exist and include a key named "password"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
                optional: false # same as default; "mysecret" must exist and include a key named "password"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
                optional: false # same as default; "mysecret" must exist and include a key named "password"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: db
  name: db-service
spec:
  ports:
  - name: mysql-service
    port: 3306
    targetPort: 3306
  selector:
    type: db
