---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: infomed-stat-cron
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/infomed-stat.ru-cron
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: infomed-stat-cron
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: infomed-stat-cron
  policy:
    semver:
      range: 1.x.x

