---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: einsteiners-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/dev/microk8s/www.einsteiners.us
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

