---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: podinfo-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo-registry
  policy:
    semver:
      range: 5.1.x
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: podinfo-registry
  namespace: flux-system
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 24h0m0s
