---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: infomed-stat-images
  namespace: flux-system
spec:
  certSecretRef:
    name: local-registry-cert
  image: registry.conn-me.ru:5000/www-server-and-expire
  interval: 24h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: infomed-stat-images
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: infomed-stat-images
  policy:
    semver:
      range: 0.x.x

