apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: learn-helm
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: ssh://git@github.com/IvanKuchin/learn-helm.git
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: learn-helm
  namespace: flux-system
spec:
  interval: 15m0s
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: learn-helm
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/ivankuchin/test-container
      tag: ghcr.io/ivankuchin/test-container:v0.0.5 # {"$imagepolicy": "flux-system:learn-helm"}
