resources:
- ../../../../base/engine_cpp/app
images:
- name: app-image
  newName: ghcr.io/ivankuchin/connme.ru-app:v1.9.0 # {"$imagepolicy": "flux-system:connme-app"}
- name: uploaders-image
  newName: ghcr.io/ivankuchin/connme.ru-uploaders:v1.9.0 # {"$imagepolicy": "flux-system:connme-uploaders"}
- name: ui-image
  newName: ghcr.io/ivankuchin/connme.ru-ui:v1.6.0 # {"$imagepolicy": "flux-system:connme-ui"}
- name: admin-image
  newName: ghcr.io/ivankuchin/connme.ru-admin:v1.0.9 # {"$imagepolicy": "flux-system:connme-admin"}
- name: www-server-image
  newName: ghcr.io/ivankuchin/www-server-and-expire:v0.1.3 # {"$imagepolicy": "flux-system:www-server"}
- name: cron-image
  newName: ghcr.io/ivankuchin/connme.ru-cron:v1.9.0 # {"$imagepolicy": "flux-system:connme-cron"}
- name: domain-name-image
  newName: ghcr.io/ivankuchin/domain-name:v0.1.3 # {"$imagepolicy": "flux-system:domain-name"}
