---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: go-migrate
  namespace: flux-system
spec:
  image: migrate/migrate
  interval: 24h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: go-migrate
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-migrate
  policy:
    semver:
      range: 4.x.x

