apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: demo.einsteiners.us-db-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo.einsteiners.us-db-pv
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #mountOptions:
  #    - hard
  nfs:
    path: /storage1/demo.einsteiners.us/mysql
    server: 172.16.17.70
