apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: demo.einsteiners.us-images-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo.einsteiners.us-images-pv
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  #mountOptions:
  #    - hard
  nfs:
    path: /storage1/demo.einsteiners.us/images
    server: 172.16.17.70
