apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: dev.infomed-stat.ru-images-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: host
  name: dev.infomed-stat.ru-images-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/ikuchin/tmp/dev.infomed-stat.ru/pv/images
    type: DirectoryOrCreate
  storageClassName: slow
