apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: dev.infomed-stat.ru-www-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: host
  name: dev.infomed-stat.ru-www-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/ikuchin/tmp/dev.infomed-stat.ru/pv/html
    type: DirectoryOrCreate
  storageClassName: slow
