apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: adminer
  name: adminer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      name: adminer-pod
      labels:
        type: adminer
    spec:
      containers:
        - name: adminer-container
          image: adminer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: adminer
  name: adminer-service
spec:
  ports:
  - name: adminer-service
    port: 8080
    targetPort: 8080
  selector:
    type: adminer
