---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: www-learn-helm-app
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./apps/prod/nj/learn-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

