---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: www-server
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/www-server-and-expire
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: www-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: www-server
  policy:
    semver:
      range: 0.x.x

