---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: go-migrate-infra
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infrastructure/prod/microk8s/go-migrate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

