apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podinfo-deployment.yaml
- imagepolicy.yaml
- registry.yaml
- image-update.yaml
images:
- name: app-image
  newName: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo-image-policy"}
