apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podinfo-deployment.yaml
images:
- name: app-image
  newName: ghcr.io/stefanprodan/podinfo:5.1.4 # {"$imagepolicy": "flux-system:podinfo-image-policy"}
