apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goaccess-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: www.connme.ru-goaccess-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www.connme.ru-goaccess-pv
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /storage_local/www.connme.ru/goaccess
    server: 192.168.170.36
