apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apachelogs-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: www.timecard.ru-apachelogs-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.timecard.ru-apachelogs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /storage_local/www.timecard.ru/apache_logs
    server: 192.168.170.36
  storageClassName: slow
