apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: www.timecard.ru-images-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.timecard.ru-images-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /storage_local/www.timecard.ru/images
    server: 192.168.170.36
  storageClassName: slow
