---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: connme-ui
  namespace: flux-system
spec:
  certSecretRef:
    name: local-registry-cert
  image: registry.conn-me.ru:5000/connme.ru-ui
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: connme-ui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: connme-ui
  policy:
    semver:
      range: 1.x.x

