apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  
  labels:
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api
  strategy:
    type: Recreate
  template:
    metadata:
      name: api-pod
      labels:
        type: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: api-volume
          configMap:
            name: api-configmap
      containers:
        - name: api-container
          image: api-image
          ports:
            - containerPort: 80
          volumeMounts:
          - name: api-volume
            mountPath: /workdir/config

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  
  labels:
    type: api
spec:
  ports:
  - name: api-service
    port: 80
    targetPort: 80
  selector:
    type: api
