---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: domain-name
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/domain-name
  interval: 24h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: domain-name
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: domain-name
  policy:
    semver:
      range: 0.x.x

