apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: dev.infomed-stat.ru-db-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: dev.infomed-stat.ru-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/c/Users/ikuchin/Downloads/dev.infomed-stat.ru/db
    type: DirectoryOrCreate
  storageClassName: slow
