apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: dev.infomed-stat.ru-www-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: dev.infomed-stat.ru-www-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/c/Users/ikuchin/Downloads/dev.infomed-stat.ru/infomed-stat.ru-ui/html
    type: DirectoryOrCreate
  storageClassName: slow
