apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.bestbounty.ru-apachelogs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: apachelogs-pvc
    namespace: www-bestbounty-ru
  nfs:
    path: /storage_local/www.bestbounty.ru/apache_logs
    server: 192.168.170.36
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.bestbounty.ru-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: db-pvc
    namespace: www-bestbounty-ru
  nfs:
    path: /storage_local/www.bestbounty.ru/mysql
    server: 192.168.170.36
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.bestbounty.ru-images-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: images-pvc
    namespace: www-bestbounty-ru
  nfs:
    path: /storage_local/www.bestbounty.ru/images
    server: 192.168.170.36
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www.bestbounty.ru-goaccess-pv
  labels:
    type: nfs
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #mountOptions:
  #    - hard
  nfs:
    path: /storage_local/www.bestbounty.ru/goaccess
    server: 192.168.170.36
  claimRef:
    name: goaccess-pvc
    namespace: www-bestbounty-ru
