apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-daily-cronjob
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 33
          volumes:
          - name: images-vol
            persistentVolumeClaim:
              claimName: images-pvc
          - name: ssh-identity-vol
            configMap:
              name: ssh-identity-secret
              defaultMode: 0400
          containers:
          - name: backup-container
            image: ikuchin/ssh-rsync-mysql-client
            env:
            - name: TZ
              value: Europe/Moscow
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: images-vol
              mountPath: /storage_local/images
              readOnly: true
            - name: ssh-identity-vol
              mountPath: /ssh-identity
            command: ["/bin/sh", "-c"]
            args: ["cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
                    && cd `mktemp -d`
                    && mysqldump --add-drop-table -Q -h db-service -u backup -pbackup www | gzip > `date +%Y%m%d%H%M%S`.gz
                    && scp -i /ssh-identity/id_rsa -o 'StrictHostKeyChecking no' *.gz ikuchin@172.16.17.70:/storage2/backup/${NAMESPACE}/mysql/
                    && scp -i /ssh-identity/id_rsa -o 'StrictHostKeyChecking no' *.gz ikuchin@192.168.168.12:/storage/ikuchin/backup/web-sites/${NAMESPACE}/mysql/
                    "]
            resources:
              limits:
                cpu: 250m
              requests:
                cpu: 50m
          restartPolicy: Never
