---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: captcha-server
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/captcha_pi
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: captcha-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: captcha-server
  policy:
    semver:
      range: 0.x.x

