apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha-deployment
  
  labels:
    type: captcha
spec:
  # do NOT scale it up. 
  # this container must keep state from providing captcha image till checking the entered code
  # there is no shared storage in the current implementation
  replicas: 1
  selector:
    matchLabels:
      type: captcha
  strategy:
    type: Recreate
  template:
    metadata:
      name: captcha-pod
      labels:
        type: captcha
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: captcha-volume
          configMap:
            name: captcha-configmap
      containers:
        - name: captcha-container
          image: captcha-image
          ports:
            - containerPort: 80
          volumeMounts:
          - name: captcha-volume
            mountPath: /workdir/config

---
apiVersion: v1
kind: Service
metadata:
  name: captcha-service
  
  labels:
    type: captcha
spec:
  ports:
  - name: captcha-service
    port: 80
    targetPort: 80
  selector:
    type: captcha
