---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: demo-einsteiners-app
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/einsteiners.us-stage
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-einsteiners-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-einsteiners-app
  filterTags:
    pattern: '^[0-9]+T[0-9]+$'
  policy:
    alphabetical:
      order: asc

