apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: www.infomed-stat.ru-db-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.infomed-stat.ru-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /storage1/www.infomed-stat.ru/mysql
    server: 172.16.17.70
  storageClassName: slow
