---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: timecard-ui
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/timecard.ru-ui
  interval: 6h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: timecard-ui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: timecard-ui
  policy:
    semver:
      range: 1.x.x

