resources:
- ../../../../base/engine_cpp/app
images:
- name: app-image
  newName: registry.conn-me.ru:5000/timecard.ru-app:v1.7.0 # {"$imagepolicy": "flux-system:timecard-app"}
- name: uploaders-image
  newName: registry.conn-me.ru:5000/timecard.ru-uploaders:v1.7.0 # {"$imagepolicy": "flux-system:timecard-uploaders"}
- name: ui-image
  newName: registry.conn-me.ru:5000/timecard.ru-ui:v1.3.1 # {"$imagepolicy": "flux-system:timecard-ui"}
- name: admin-image
  newName: registry.conn-me.ru:5000/timecard.ru-admin:v1.0.2 # {"$imagepolicy": "flux-system:timecard-admin"}
- name: www-server-image
  newName: registry.conn-me.ru:5000/www-server-and-expire:v0.1.3 # {"$imagepolicy": "flux-system:timecard-images"}
- name: cron-image
  newName: registry.conn-me.ru:5000/timecard.ru-cron:v1.7.0 # {"$imagepolicy": "flux-system:timecard-cron"}
