---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: inspiremeweddingplanner-w-influencers-com
  namespace: flux-system
spec:
  image: ghcr.io/ivankuchin/inspiremeweddingplanner.w-influencers.com
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: inspiremeweddingplanner-w-influencers-com
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: inspiremeweddingplanner-w-influencers-com
  policy:
    semver:
      range: 0.x.x

