---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo-app
  namespace: flux-system
spec:
  interval: 3m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo

