- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: templates-vol
    persistentVolumeClaim:
      claimName: templates-pvc
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: templates-vol
    mountPath: /usr/local/share/www/templates
