resources:
- ../../../../base/engine_cpp/app
patches:
  - target:
      kind: Deployment
      name: ui-deployment
    path: ui-deployment-add-volume.yaml
  - target:
      kind: Deployment
      name: app-deployment
    path: app-deployment-add-volume.yaml
images:
- name: app-image
  newName: infomed-stat.ru-app
- name: uploaders-image
  newName: infomed-stat.ru-uploaders
- name: ui-image
  newName: infomed-stat.ru-ui
- name: admin-image
  newName: infomed-stat.ru-admin
- name: www-server-image
  newName: ghcr.io/ivankuchin/www-server-and-expire:latest
- name: cron-image
  newName: infomed-stat.ru-cron
- name: domain-name-image
  newName: ghcr.io/ivankuchin/domain-name:latest
