---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-timecard-app
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./apps/prod/mow/demo.timecard.ru
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

