---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-image-updater-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/dev/microk8s/podinfo-image-updater
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

