---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: connectopia-app
  namespace: flux-system
spec:
  image: ghcr.io/connectopia-social/www.connectopia.social-api
  interval: 15m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: connectopia-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: connectopia-app
  policy:
    semver:
      range: 0.x.x

