---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: inspiremeweddingplanner-w-influencers-com-app
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./apps/prod/microk8s/inspiremeweddingplanner.w-influencers.com
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

