---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: bestbounty-uploaders
  namespace: flux-system
spec:
  certSecretRef:
    name: local-registry-cert
  image: registry.conn-me.ru:5000/bestbounty.ru-uploaders
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bestbounty-uploaders
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bestbounty-uploaders
  policy:
    semver:
      range: 1.x.x

