apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: www.einsteiners.us-db-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: nfs
  name: www.einsteiners.us-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /storage_local/www.einsteiners.us/mysql
    server: 192.168.170.36
  storageClassName: slow
