apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://github.com/ivankuchin/k8s-flux
  secretRef:
    name: flux-system
  branch:
    name: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/prod/nj
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system