apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploaders-deployment
  
  labels:
    type: uploaders
spec:
  replicas: 1
  selector:
    matchLabels:
      type: uploaders
  strategy:
    type: Recreate
  template:
    metadata:
      name: uploaders-pod
      labels:
        type: uploaders
    spec:
      securityContext:
        fsGroup: 33    # --- assign group ID to mounted volume
      hostAliases:
      - ip: "172.16.17.68"
        hostnames:
        - "mail"
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: images-vol
          persistentVolumeClaim:
            claimName: images-pvc
        - name: logs-app-vol
          emptyDir: {}
        - name: app-secret
          configMap:
            name: app-secret
      containers:
        - name: uploaders-container
          image: uploaders-image
          ports:
            - containerPort: 80
          volumeMounts:
          - name: images-vol
            mountPath: /home/httpd/images/html
          - name: logs-app-vol
            mountPath: /usr/local/share/www/log
          - name: app-secret
            mountPath: /usr/local/share/www/config/secret

        - name: log-app-container
          image: busybox-image
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          volumeMounts:
          - name: logs-app-vol
            mountPath: /var/log
          command: ["/bin/sh"]
          args: ["-c", "touch /var/log/backend.log; tail -n+1 -f /var/log/backend.log"]

      initContainers:
      - name: init-mysql
        image: busybox-image
        command: ['sh', '-c', 'until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: uploaders-service
  
  labels:
    type: uploaders
spec:
  ports:
  - name: uploaders-service
    port: 80
    targetPort: 80
  selector:
    type: uploaders
