---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: domain-name-infra
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./infrastructure/prod/mow/domain-name
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

