---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: connme-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/dev/m3/www.connme.ru
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

